# --------------------------------------------------
# HOMESEER LINUX SERVER
# --------------------------------------------------
# This container hosts the HomeSeer V4 server.
# This config will create standalone 'homeseer-data'
# docker volume to store all homeseer runtime
# files. (logs, config, backups, app files)
#
# Disclaimers:
# --------------
# This docker container is not supported, sponsored
# or directly affiliated with Homeseer
# (https://homeseer.com).
#
# --------------------------------------------------
#    (Developed with ♥ by SavageSoftware, LLC.)
# --------------------------------------------------
version: '3.8'

volumes:
  homeseer_data_trial:
    name: homeseer_data_trial

services:
  homeseer_trial:
    container_name: try_homeseer_trial
    image: wpiman/homeseer:4.2.22.94_mono200_shutdownchanges
    hostname: homeseer_trial
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 82:80
    environment:
      TZ: America/New_York
      LANG: en_US.UTF-8
    volumes:
      - homeseer_data_trial:/homeseer
